services:
  api:
    environment:
      NODE_ENV: development

  ui:
    environment:
      NODE_ENV: development

  mcp:
    environment:
      NODE_ENV: development

  worker:
    environment:
      NODE_ENV: development
